Multiple Records are not showing in Slider
ankitzalani/currybhari-view pull request #7
Opened 2016-11-09 17:21 UTC by PANKAJKHANDKAR

2016-11-09 17:36 UTC, ankitzalani requested changes

2016-11-09 17:36 UTC, ankitzalani commented on app/views/slider.html
> +                        <div class="item active" ng-repeat="product in getProducts()"">
If you do this, more than one item will be active at a time.

2016-11-12 17:36 UTC, PANKAJKHANDKAR commented
ok

2016-11-13 06:55 UTC, ankitzalani approved these changes

2016-11-13 06:56 UTC, ankitzalani approved these changes

2016-11-13 07:02 UTC, closed without merging